#!/usr/bin/env python3
"""
Bootstrap entry files from cities.json.

Creates empty data/city-entries/{slug}.html and data/testimonials/{slug}.json
for every city in cities.json. Safe to run multiple times (skips existing files).

Usage:
    python scripts/bootstrap-entries.py
"""

import json
import os
from pathlib import Path


def bootstrap_entries():
    script_dir = Path(__file__).parent.parent  # my-poland-journey/
    cities_json = script_dir / "data" / "cities.json"
    entries_dir = script_dir / "data" / "city-entries"
    testimonials_dir = script_dir / "data" / "testimonials"

    # Create directories if they don't exist
    entries_dir.mkdir(parents=True, exist_ok=True)
    testimonials_dir.mkdir(parents=True, exist_ok=True)

    # Read cities.json
    with open(cities_json) as f:
        cities = json.load(f)

    created_entries = 0
    created_testimonials = 0
    skipped = 0

    for city in cities:
        city_id = city["id"]

        # Create entry file
        entry_path = entries_dir / f"{city_id}.html"
        if not entry_path.exists():
            entry_path.write_text(
                f"<!-- {city['name']} encyclopedia entry (generated by bootstrap-entries.py) -->\n"
            )
            created_entries += 1
        else:
            skipped += 1

        # Create testimonials file
        testimonials_path = testimonials_dir / f"{city_id}.json"
        if not testimonials_path.exists():
            testimonials_path.write_text('{\n  "embeds": []\n}\n')
            created_testimonials += 1
        else:
            skipped += 1

    print(
        f"✓ Created {created_entries} entry files (data/city-entries/*.html)"
    )
    print(
        f"✓ Created {created_testimonials} testimonials files (data/testimonials/*.json)"
    )
    print(f"⊘ Skipped {skipped} existing files")


if __name__ == "__main__":
    bootstrap_entries()
